# Generated by Django 6.0.5 on 2026-05-12 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='題目內容')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='選項內容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否為正確答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='所屬題目')),
            ],
        ),
        migrations.CreateModel(
            name='QuizRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.IntegerField(verbose_name='作答時間(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='測驗時間')),
                ('wrong_questions', models.ManyToManyField(blank=True, to='quiz.question', verbose_name='答錯的題目')),
            ],
        ),
    ]
