# Generated by Django 6.0.5 on 2026-05-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('易', '易 (Easy)'), ('中', '中 (Medium)'), ('難', '難 (Hard)')], default='中', max_length=1, verbose_name='難易度'),
        ),
    ]
